ui.customnotebutton.title=Add a Custom Memo
ui.customnotebutton.limit_title=Memo Limit Reached
ui.customnotebutton.limit_text=You can discard old memos to make room for more. All of your current custom memos can be reviewed in your shift log.
ui.customnotebutton.desc=Custom Memos let you record anything you'd like in the shift log.\n\nThey can be just text on its own, or they can be associated with a Factory Sector, one of your items, or a type of chemical/memo/badge.
ui.customnotebutton.new_text=New Text Memo
ui.customnotebutton.new_text_title=Write a title for this custom text memo:
ui.customnotebutton.new_floor=New Factory Sector Memo
ui.customnotebutton.new_floor_prompt=Select a sector of the Factory to associate this memo with.
ui.customnotebutton.new_floor_title=Write a title for this custom memo for sector %d:
ui.customnotebutton.new_inv=New Utility Cart Item Memo
ui.customnotebutton.new_inv_prompt=Select a Memo Item
ui.customnotebutton.new_item_title=Write a title for this custom memo for the item:\n_%s_
ui.customnotebutton.new_type=New Item Type Memo
ui.customnotebutton.new_type_prompt=Select a type of item you'd like to associate this memo with.
ui.customnotebutton$customnotewindow.edit_title=Edit Title
ui.customnotebutton$customnotewindow.add_text=Add Text
ui.customnotebutton$customnotewindow.edit_text=Edit Text
ui.customnotebutton$customnotewindow.delete=Delete
ui.customnotebutton$customnotewindow.delete_warn=Are you sure you want to delete this custom memo?
ui.customnotebutton$customnotewindow.confirm=Confirm
ui.customnotebutton$customnotewindow.cancel=Cancel

ui.quickslotbutton.select_item=Quickslot an item

ui.talentspane.tier=pay grade %d
ui.talentspane.unlock_tier2=Complete 6 shifts to unlock more skills.
ui.talentspane.unlock_tier3=Complete 12 shifts and submit the second supervisor's approval form to unlock more skills.
ui.talentspane.unlock_tier4=Complete 20 shifts and submit the fourth supervisor's approval form to unlock more skills.
ui.talentspane.random_title=Random Skills
ui.talentspane.random_sure=Are you sure you want to spend these training hours without union approval?
ui.talentspane.random_yes=Yes, spend them all.
ui.talentspane.random_one=Just spend one without union approval.
ui.talentspane.random_no=I'll decide later.

ui.toolbar.quickslot_prompt=Select a Quickslot
ui.toolbar.quickslot_select=Select Quickslot
ui.toolbar.quickslot_assign=Assign Quickslot
ui.toolbar.quickslot_cancel=Cancel
ui.toolbar.container_prompt=Select a Container
ui.toolbar.container_select=Select Container
ui.toolbar.container_cancel=Cancel
ui.toolbar.container_empty=That container is empty!
ui.toolbar.item_prompt=Select an Item
ui.toolbar.item_select=Select Item
ui.toolbar.item_use=Quick-use Item
ui.toolbar.item_cancel=Cancel
ui.toolbar.examine_prompt=Press again to search\nPress a tile to examine

ui.updatenotification.title=Update
ui.updatenotification$wndupdate.title=An Update is Available!
ui.updatenotification$wndupdate.versioned_title=Update Available: %s
ui.updatenotification$wndupdate.desc=Shattered Pixel Factory is regularly updated with overhauls to existing game content, or entirely new content!\n\nGame balance is also frequently improved in game updates, so that specific items/janitors/hazards aren't too strong or too weak.\n\nUpdates also include fixes for bugs and other various stability improvements.
ui.updatenotification$wndupdate.button=Go To Update Page