plants.blandfruitbush.name=calcified grime
plants.blandfruitbush.desc=A stubborn pile of factory grime. It tastes like caked dust and machine oil. It is gross and unsubstantial but isn't immediately toxic. Perhaps it could be dissolved.
plants.blandfruitbush.discover_hint=You can find this mess randomly in the factory.
plants.blandfruitbush$seed.name=clump of calcified grime

plants.blindweed.name=flash-bang mold
plants.blindweed.desc=Upon being disturbed, this peculiar mold bursts in a bright flash of spark and light. The flash is strong enough to disorient for several seconds.
plants.blindweed.warden_desc=_The Bio-Hazard Tech_ will channel this mold's spark into a temporary optical camouflage, instead of being disoriented.
plants.blindweed$seed.name=spore of flash-bang mold

plants.mageroyal.name=neutralizing solvent puddle
plants.mageroyal.refreshed=You feel decontaminated.
plants.mageroyal.desc=This chemical puddle contains a compound known for its properties as a strong neutralizing agent. Anything that steps in it will be cleansed of many negative hazardous effects.
plants.mageroyal.warden_desc=In addition to the neutralizing effect, _the Bio-Hazard Tech_ will become temporarily immune to all area-bound hazards when stepping in the solvent.
plants.mageroyal$seed.name=capsule of neutralizing solvent

plants.earthroot.name=heavy-duty sealant
plants.earthroot.desc=When a worker touches this sealant, it rapidly hardens, creating a kind of immobile synthetic ppe around them.
plants.earthroot.warden_desc=The sealant will adjust with _the Bio-Hazard Tech_, providing mobile synthetic ppe.
plants.earthroot$seed.name=tube of heavy-duty sealant
plants.earthroot$armor.name=sealant suit
plants.earthroot$armor.desc=A thick, immobile layer made of rapid-hardening synthetic sealant.\n\nThis sealant suit will block %d damage from any physical hit, until it eventually runs out of durability and cracks off.\n\nAs the suit is immobile, moving will cause it to break apart and be lost.\n\nArmor remaining: %d.

plants.fadeleaf.name=displacement ooze
plants.fadeleaf.desc=Stepping in this space-time warping ooze will teleport any employee to a random place on the current factory floor.
plants.fadeleaf.warden_desc=The teleportation effect of this ooze is more potent for _the Bio-Hazard Tech_, teleporting them back to the end of the previous factory sector.
plants.fadeleaf$seed.name=glob of displacement ooze

plants.firebloom.name=phosphorus sludge
plants.firebloom.desc=When something touches this volatile sludge, it bursts into industrial flames.
plants.firebloom.warden_desc=When they step on phosphorus sludge, _the Bio-Hazard Tech_ will be briefly imbued with thermal energy instead of being burned.
plants.firebloom$seed.name=glob of phosphorus sludge

plants.icecap.name=liquid nitrogen spill
plants.icecap.desc=Upon being touched, this spill lets out a puff of freezing vapor. The freezing effect is much stronger if the environment is wet.
plants.icecap.warden_desc=When they step in a liquid nitrogen spill, _the Bio-Hazard Tech_ will be briefly imbued with cryogenic frost instead of being harmed.
plants.icecap$seed.name=capsule of liquid nitrogen

plants.plant.warden_desc=This chemical has no special effect when used by the Bio-Hazard Tech.
plants.plant.discover_hint=You can find this chemical randomly in the factory, or deploy it from its associated capsule.
plants.plant$seed.seed_of=capsule of %s
plants.plant$seed.ac_plant=DEPLOY
plants.plant$seed.info=Throw this capsule to the place where you want to deploy the chemical.\n\n%s
plants.plant$seed$placeholder.name=capsule

plants.rotberry.name=toxic sludge
plants.rotberry.desc=A nasty bubbling puddle of toxic sludge. Over a few years, it might mutate into something much worse. When disturbed, a young puddle of sludge will produce a small puff of toxic gas.
plants.rotberry.warden_desc=Normally this sludge only produces a little gas when disturbed, but _the Bio-Hazard Tech_ is able to harness energy from it to temporarily boost their strength!
plants.rotberry.discover_hint=You can deploy this from its associated capsule during a specific maintenance task.
plants.rotberry$seed.name=capsule of toxic sludge
plants.rotberry$seed.discover_hint=You can find this item during a specific maintenance task.

plants.sorrowmoss.name=corrosive rust fungus
plants.sorrowmoss.desc=A nasty fungus with razor-sharp edges, coated with a deadly corrosive venom.
plants.sorrowmoss.warden_desc=When they trample a corrosive rust fungus, _the Bio-Hazard Tech_ will be briefly imbued with toxin instead of being harmed.
plants.sorrowmoss$seed.name=spore of corrosive rust fungus

plants.starflower.name=precision ball bearing
plants.starflower.desc=A rare pristine component, this precision ball bearing is said to grant flawless efficiency to whomever touches it.
plants.starflower.warden_desc=In addition to being hyper-efficient, _the Bio-Hazard Tech_ will gain a significant amount of equipment recharging when they touch a precision ball bearing.
plants.starflower$seed.name=box of precision ball bearings

plants.stormvine.name=anti-grav residue
plants.stormvine.desc=Gravity affects this anti-friction residue strangely, allowing its whispy blue tendrils to 'hang' on the air. Anything caught in the residue is affected by this, and becomes disoriented.
plants.stormvine.warden_desc=_The Bio-Hazard Tech_ is able to control the gravitational effect of anti-grav residue, and will briefly levitate when they step in it.
plants.stormvine$seed.name=glob of anti-grav residue

plants.sungrass.name=curative aloe gel
plants.sungrass.desc=Curative aloe gel is renowned for its slow but effective healing properties when applied to chemical burns.
plants.sungrass.warden_desc=_The Bio-Hazard Tech_ can receive healing from curative aloe gel even if they move away from it.
plants.sungrass$seed.name=capsule of curative aloe gel
plants.sungrass$health.name=first-aid healing
plants.sungrass$health.desc=This aloe gel possesses excellent healing properties, though it is much slower than a first-aid spray.\n\nMoving out of the gel will break the healing effect.\n\nHealing remaining: %d.

plants.swiftthistle.name=caffeine spill
plants.swiftthistle.desc=When stepped in, this concentrated caffeine spill will briefly accelerate the flow of time around it, allowing the worker to perform several actions instantly.
plants.swiftthistle.warden_desc=In addition to gaining instantaneous actions, _the Bio-Hazard Tech_ will also get a brief haste boost when stepping in a caffeine spill.
plants.swiftthistle$seed.name=capsule of concentrated caffeine
plants.swiftthistle$timebubble.name=caffeine rush
plants.swiftthistle$timebubble.desc=A small bubble of accelerated time, allowing actions to be performed instantly. Attacking or using equipment will break this effect however.\n\nTurns remaining: %s.
